[tool.poetry]
name = "homework13-1"
version = "0.1.0"
description = ""
authors = ["dasha gromova <darya.gromova8559@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
